<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/1_Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy


In [2]:
import numpy

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [19]:
lst = [[1,2,3],
       [1,2,3],
       [1,2,3]]

In [20]:
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [21]:
type(lst)

list

In [22]:
arr=np.array(lst)

In [23]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:

type(arr)

numpy.ndarray

In [25]:
arr.ndim

2

In [26]:

arr.shape


(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

In [30]:
zeros=np.zeros((3,5))

In [31]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
ones=np.ones((6,3))

In [33]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])