<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:

arr=np.array([1,2,3,4,5,6])

In [6]:
arr


array([1, 2, 3, 4, 5, 6])

In [7]:
arr + 1

array([2, 3, 4, 5, 6, 7])

In [9]:
arr - 1

array([0, 1, 2, 3, 4, 5])

In [10]:
arr * 5

array([ 5, 10, 15, 20, 25, 30])

In [11]:
arr % 2

array([1, 0, 1, 0, 1, 0])

In [12]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [13]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36])

In [14]:
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr = arr + 1

In [16]:
arr

array([2, 3, 4, 5, 6, 7])

In [17]:
arr +=2

In [18]:
arr

array([4, 5, 6, 7, 8, 9])

In [19]:
arr.max()

9

In [20]:
arr.min()

4

In [22]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.max(axis=0) # max element column wise

array([7, 8, 9])

In [26]:
arr.max(axis=1) # min element row wise

array([3, 6, 9])

In [28]:

arr.min(axis=1)

array([1, 4, 7])

In [29]:
arr.min(axis=0)

array([1, 2, 3])

In [30]:
arr.sum()

45