<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])


In [5]:
arr2 = np.array([[8,7,6,5],[4,3,2,1]])

In [6]:
np.vstack((arr1,arr2)) # order specific

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [7]:
np.hstack((arr1,arr2)) # order specific

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [11]:
arr=np.concatenate((arr1,arr2), axis=0 ) # for 0 vertical stack and for axis =1 horizontal stack

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [15]:
np.hsplit((arr),2) # 2 indicates 2 half similarly vsplit

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [16]:
np.vsplit((arr),2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]