<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Multiple_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [4]:
arr1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [15]:
arr2=np.array([[9,8,7]
                ,[6,5,4],
                 [3,2,1]])

In [6]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [8]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [11]:
arr3=np.array([[9,8,7,5],[6,5,4,3],[3,2,1,5]]) # if order is diff we cannot perform arithmetic operations

In [16]:
arr2 * arr1

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [17]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [18]:
arr=np.array([1,2,3,4,5])

In [19]:
arr[:]

array([1, 2, 3, 4, 5])

In [20]:
arr[:-2]

array([1, 2, 3])

In [21]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr1[:,:1] #1st column

array([[1],
       [4],
       [7]])

In [25]:
arr1[:1,:]

array([[1, 2, 3]])

In [26]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [28]:
arr1[1:2,1:2] # 2nd row and 2nd column


array([[5]])

In [30]:
arr1[1:,1:] # except the first row and first column

array([[5, 6],
       [8, 9]])