<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Reshape_and_Random_no_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.random((3,3))

array([[0.44017926, 0.79773062, 0.23770697],
       [0.36026086, 0.58064577, 0.04034718],
       [0.00428102, 0.01740741, 0.28507688]])

In [3]:
np.random.random()

0.5827895889397297

In [6]:
if np.random.random() > 0.5:
  print("Run function")

else:
  print("Do not")

Do not


In [7]:
np.arange(1,10,1) #if 10 it will generate till 9 only

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10,3)

array([1, 4, 7])

In [9]:
np.linspace(1,10,10) #how many values u want in between equisidtant

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [12]:
arr=np.random.random((4,3))

In [13]:
arr

array([[0.82976298, 0.35295185, 0.11700027],
       [0.01675916, 0.44016612, 0.26521589],
       [0.28862889, 0.41378806, 0.40063502],
       [0.27074661, 0.91503201, 0.87022543]])

In [14]:
np.reshape(arr,(3,4))

array([[0.82976298, 0.35295185, 0.11700027, 0.01675916],
       [0.44016612, 0.26521589, 0.28862889, 0.41378806],
       [0.40063502, 0.27074661, 0.91503201, 0.87022543]])

In [15]:
np.reshape(arr,(6,2)) # u should not change the size of array or number of elements

array([[0.82976298, 0.35295185],
       [0.11700027, 0.01675916],
       [0.44016612, 0.26521589],
       [0.28862889, 0.41378806],
       [0.40063502, 0.27074661],
       [0.91503201, 0.87022543]])

In [16]:
arr.flatten() # it changes to 1 dimension

array([0.82976298, 0.35295185, 0.11700027, 0.01675916, 0.44016612,
       0.26521589, 0.28862889, 0.41378806, 0.40063502, 0.27074661,
       0.91503201, 0.87022543])