<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [11]:
arr[:1 , :]

array([[1, 2, 3, 4]])

In [12]:
arr[1: , :] # everything except row 1 same goes for column

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [13]:
arr[1:, 1:2] # index 2 not included

array([[6],
       [7],
       [3]])