<a href="https://colab.research.google.com/github/jestfulfalcon/test1/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
arr=np.array([[7,5,6,8,9],[2,4,5,3,1,],[2,4,8,5,9]])

In [3]:
arr

array([[7, 5, 6, 8, 9],
       [2, 4, 5, 3, 1],
       [2, 4, 8, 5, 9]])

In [5]:
np.sort(arr , axis=1, kind = 'mergesort') # sorted row wise

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [2, 4, 5, 8, 9]])

In [6]:
np.sort(arr , axis=0, kind = 'mergesort') # sorted row wise

array([[2, 4, 5, 3, 1],
       [2, 4, 6, 5, 9],
       [7, 5, 8, 8, 9]])

In [7]:
np.sort(arr , axis=1, kind = 'quicksort')

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [2, 4, 5, 8, 9]])